### ISSUE TITLE
TODO: Reimplement this plugin

### ISSUE THREAD

**Issue by shiraji** [shiraji/emoji#18]
* ~Ask GitHub about Emoji image license (If I cannot use them, I need to find other way to do this)~
- [x] Migrate to [GitHub Emoji API](https://api.github.com/emojis)
- [x] Create mechanize up to date Emoji (generate json and download icons at CI?)
- [x] Implement features that support string/comment, same as https://github.com/shiraji/yet-another-emoji-support
* ~Add test cases~ Do this in other PR

**Comment by shiraji** [comment]
It seems GitHub cannot answer the license thing, quickly. In stead of using their images, I will use emoji unicode, like what [my other plugin](https://github.com/shiraji/yet-another-emoji-support) is doing.
